services:
    Gpec\GpecBundle\GpecClientFactory:
        public: true

    Gpec\GpecBundle\Service\GpecService:
        arguments:
            $clientFactory: '@Gpec\GpecBundle\GpecClientFactory'
        public: true